apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-server
  namespace: argocd
spec:
  secretName: argocd-server-tls
  dnsNames:
  - argocd.oremuslabs.app
  issuerRef:
    kind: ClusterIssuer
    name: cloudflare-dns
