global:
  revisionHistoryLimit: 5

configs:
  params:
    controller.operation.processors: "10"
    controller.status.processors: "20"
    applicationsetcontroller.log.format: json
  cm:
    url: https://argocd.oremuslabs.app
    timeout.reconciliation: 60s
    admin.enabled: "true"
    # Automation login for Codex CLI flows – allows API tokens + password auth
    accounts.codex-cli: login,apiKey
    accounts.codex-cli.enabled: "true"
    ui.applicationset.enabled: "true"
    # Allow Argo CD to manage Endpoints/EndpointSlices so external proxies can be created.
    # Keep only the non-network exclusions we actually need.
    resource.exclusions: |
      - apiGroups:
        - coordination.k8s.io
        kinds:
        - Lease
      - apiGroups:
        - authentication.k8s.io
        - authorization.k8s.io
        kinds:
        - SelfSubjectReview
        - TokenReview
        - LocalSubjectAccessReview
        - SelfSubjectAccessReview
        - SelfSubjectRulesReview
        - SubjectAccessReview
      - apiGroups:
        - certificates.k8s.io
        kinds:
        - CertificateSigningRequest
      - apiGroups:
        - cert-manager.io
        kinds:
        - CertificateRequest
      - apiGroups:
        - cilium.io
        kinds:
        - CiliumIdentity
        - CiliumEndpoint
        - CiliumEndpointSlice
      - apiGroups:
        - kyverno.io
        - reports.kyverno.io
        - wgpolicyk8s.io
        kinds:
        - PolicyReport
        - ClusterPolicyReport
        - EphemeralReport
        - ClusterEphemeralReport
        - AdmissionReport
        - ClusterAdmissionReport
        - BackgroundScanReport
        - ClusterBackgroundScanReport
        - UpdateRequest
    oidc.config: |
      name: EntraID
      issuer: https://login.microsoftonline.com/abfcbee8-658f-4ab3-97f5-9b357e0f8cda/v2.0
      # Load client ID/secret from argocd-secret keys (argocd substitution)
      clientID: $oidc.azure.clientId
      clientSecret: $oidc.azure.clientSecret
      requestedScopes:
        - openid
        - profile
        - email
        - offline_access
      requestedIDTokenClaims:
        groups:
          essential: true
      cliClientID: $oidc.azure.clientId
    resource.customizations.health.apps_Deployment: |
      hs = {}
      if obj.status ~= nil and obj.status.availableReplicas ~= nil and obj.status.replicas ~= nil and obj.status.availableReplicas == obj.status.replicas then
        hs.status = "Healthy"
      else
        hs.status = "Progressing"
      end
      return hs
    resource.customizations.health.serving.kserve.io_InferenceService: |
      hs = {}
      if obj.status ~= nil and obj.status.conditions ~= nil then
        for _, condition in ipairs(obj.status.conditions) do
          if condition.type == "Ready" then
            if condition.status == "True" then
              hs.status = "Healthy"
              hs.message = condition.message or condition.reason or "Ready"
              return hs
            elseif condition.status == "False" then
              hs.status = "Degraded"
              hs.message = condition.message or condition.reason or "Not Ready"
              return hs
            else
              hs.status = "Progressing"
              hs.message = condition.message or condition.reason or "Reconciling"
              return hs
            end
          end
        end
      end
      hs.status = "Progressing"
      hs.message = "Waiting for Ready condition"
      return hs
    resource.customizations: |
      "*":
        ignoreDifferences: |
          jsonPointers:
            - /status
      ConfigMap:
        ignoreDifferences: |
          jqPathExpressions:
            - '.metadata.annotations."cluster-autoscaler.kubernetes.io/last-updated"'
            - '.metadata.annotations."control-plane.alpha.kubernetes.io/leader"'
      Endpoints:
        ignoreDifferences: |
          jsonPointers:
            - /metadata
            - /subsets
      discovery.k8s.io/EndpointSlice:
        ignoreDifferences: |
          jsonPointers:
            - /metadata
            - /endpoints
            - /ports
      apps/ReplicaSet:
        ignoreDifferences: |
          jqPathExpressions:
            - '.metadata.annotations."deployment.kubernetes.io/desired-replicas"'
            - '.metadata.annotations."deployment.kubernetes.io/max-replicas"'
            - '.metadata.annotations."rollout.argoproj.io/desired-replicas"'
      argoproj.io/Application:
        ignoreDifferences: |
          jqPathExpressions:
            - '.metadata.annotations."notified.notifications.argoproj.io"'
            - '.metadata.annotations."argocd.argoproj.io/refresh"'
            - '.metadata.annotations."argocd.argoproj.io/hydrate"'
            - '.operation'
      argoproj.io/Rollout:
        ignoreDifferences: |
          jqPathExpressions:
            - '.metadata.annotations."notified.notifications.argoproj.io"'
      autoscaling/HorizontalPodAutoscaler:
        ignoreDifferences: |
          jqPathExpressions:
            - '.metadata.annotations."autoscaling.alpha.kubernetes.io/behavior"'
            - '.metadata.annotations."autoscaling.alpha.kubernetes.io/conditions"'
            - '.metadata.annotations."autoscaling.alpha.kubernetes.io/metrics"'
            - '.metadata.annotations."autoscaling.alpha.kubernetes.io/current-metrics"'
      serving.kserve.io/InferenceService:
        ignoreDifferences: |
          jsonPointers:
            - /metadata/annotations/serving.kserve.io~1deploymentMode
  repositories:
      ol-kubernetes-cluster:
        url: https://github.com/Oremus-Labs/ol-kubernetes-cluster.git
  rbac:
    policy.default: role:readonly
    policy.matchMode: glob
    scopes: '[groups]'
    policy.csv: |
      # Admins -> ArgoCD admin
      p, role:admin, *, *, *, allow
      p, role:admin, applicationsets, *, *, allow
      p, role:admin, applicationsets/*, *, *, allow
      p, role:admin, applicationset, *, *, allow
      g, cc878aef-3307-40f8-862b-07b26cedf6cd, role:admin
      # Developers -> ArgoCD developer
      p, role:developer, applications, get, */*, allow
      p, role:developer, applications, create, */*, allow
      p, role:developer, applications, update, */*, allow
      p, role:developer, applications, delete, */*, allow
      p, role:developer, applications, sync, */*, allow
      p, role:developer, projects, get, */*, allow
      p, role:developer, applicationsets, *, *, allow
      p, role:developer, applicationsets/*, *, *, allow
      p, role:developer, applicationset, *, *, allow
      g, f30d366c-0e05-403e-b5d6-66b9f8133d93, role:developer
      # Readonly -> ArgoCD read-only
      p, role:readonly, applications, get, */*, allow
      p, role:readonly, clusters, get, *, allow
      p, role:readonly, repositories, get, *, allow
      p, role:readonly, applicationsets, get, *, allow
      p, role:readonly, applicationsets/*, get, *, allow
      p, role:readonly, applicationset, get, *, allow
      g, 144a37fa-cc9d-4fc9-bf8a-a09999818504, role:readonly
      # Codex automation account -> full admin
      g, codex-cli, role:admin

controller:
  replicas: 1
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi

repoServer:
  replicas: 1
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

applicationSet:
  replicaCount: 1
  podAnnotations:
    oremus-labs.com/component: applicationset

server:
  extraArgs:
  - --insecure
  # extraEnv is not required when Argo substitutes from argocd-secret keys
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  service:
    type: ClusterIP
  autoscaling:
    enabled: false
  ingress:
    enabled: false
    tls: []

notifications:
  metrics:
    enabled: true

redis:
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 256Mi
  volumeMounts:
  - name: redis-data
    mountPath: /data
  volumes:
  - name: redis-data
    persistentVolumeClaim:
      claimName: argocd-redis
