global:
  revisionHistoryLimit: 5

configs:
  params:
    controller.operation.processors: "10"
    controller.status.processors: "20"
    applicationsetcontroller.log.format: json
  cm:
    url: https://argocd.oremuslabs.app
    timeout.reconciliation: 60s
    admin.enabled: "true"
    oidc.config: |
      name: EntraID
      issuer: https://login.microsoftonline.com/abfcbee8-658f-4ab3-97f5-9b357e0f8cda/v2.0
      # Load client ID/secret from argocd-secret keys (argocd substitution)
      clientID: $oidc.azure.clientId
      clientSecret: $oidc.azure.clientSecret
      requestedScopes:
        - openid
        - profile
        - email
        - offline_access
      requestedIDTokenClaims:
        groups:
          essential: true
      cliClientID: $oidc.azure.clientId
    resource.customizations.health.apps_Deployment: |
      hs = {}
      if obj.status ~= nil and obj.status.availableReplicas ~= nil and obj.status.replicas ~= nil and obj.status.availableReplicas == obj.status.replicas then
        hs.status = "Healthy"
      else
        hs.status = "Progressing"
      end
      return hs
    resource.customizations: |
      "*":
        ignoreDifferences: |
          jsonPointers:
            - /status
      ConfigMap:
        ignoreDifferences: |
          jqPathExpressions:
            - '.metadata.annotations."cluster-autoscaler.kubernetes.io/last-updated"'
            - '.metadata.annotations."control-plane.alpha.kubernetes.io/leader"'
      Endpoints:
        ignoreDifferences: |
          jsonPointers:
            - /metadata
            - /subsets
      discovery.k8s.io/EndpointSlice:
        ignoreDifferences: |
          jsonPointers:
            - /metadata
            - /endpoints
            - /ports
      apps/ReplicaSet:
        ignoreDifferences: |
          jqPathExpressions:
            - '.metadata.annotations."deployment.kubernetes.io/desired-replicas"'
            - '.metadata.annotations."deployment.kubernetes.io/max-replicas"'
            - '.metadata.annotations."rollout.argoproj.io/desired-replicas"'
      argoproj.io/Application:
        ignoreDifferences: |
          jqPathExpressions:
            - '.metadata.annotations."notified.notifications.argoproj.io"'
            - '.metadata.annotations."argocd.argoproj.io/refresh"'
            - '.metadata.annotations."argocd.argoproj.io/hydrate"'
            - '.operation'
      argoproj.io/Rollout:
        ignoreDifferences: |
          jqPathExpressions:
            - '.metadata.annotations."notified.notifications.argoproj.io"'
      autoscaling/HorizontalPodAutoscaler:
        ignoreDifferences: |
          jqPathExpressions:
            - '.metadata.annotations."autoscaling.alpha.kubernetes.io/behavior"'
            - '.metadata.annotations."autoscaling.alpha.kubernetes.io/conditions"'
            - '.metadata.annotations."autoscaling.alpha.kubernetes.io/metrics"'
            - '.metadata.annotations."autoscaling.alpha.kubernetes.io/current-metrics"'
    # Override chart defaults that add unsupported ignoreResourceUpdates entries (not supported by this Argo CD version)
    resource.customizations.ignoreResourceUpdates.all: ""
    resource.customizations.ignoreResourceUpdates.ConfigMap: ""
    resource.customizations.ignoreResourceUpdates.Endpoints: ""
    resource.customizations.ignoreResourceUpdates.apps_ReplicaSet: ""
    resource.customizations.ignoreResourceUpdates.argoproj.io_Application: ""
    resource.customizations.ignoreResourceUpdates.argoproj.io_Rollout: ""
    resource.customizations.ignoreResourceUpdates.autoscaling_HorizontalPodAutoscaler: ""
    resource.customizations.ignoreResourceUpdates.discovery.k8s.io_EndpointSlice: ""
  repositories:
    ol-kubernetes-cluster:
      url: https://github.com/Oremus-Labs/ol-kubernetes-cluster.git
  rbac:
    policy.default: role:readonly
    policy.csv: |
      # Admins -> ArgoCD admin
      g, cc878aef-3307-40f8-862b-07b26cedf6cd, role:admin
      # Developers -> ArgoCD developer
      p, role:developer, applications, get, */*, allow
      p, role:developer, applications, create, */*, allow
      p, role:developer, applications, update, */*, allow
      p, role:developer, applications, delete, */*, allow
      p, role:developer, applications, sync, */*, allow
      p, role:developer, projects, get, */*, allow
      g, f30d366c-0e05-403e-b5d6-66b9f8133d93, role:developer
      # Readonly -> ArgoCD read-only
      p, role:readonly, applications, get, */*, allow
      p, role:readonly, clusters, get, *, allow
      p, role:readonly, repositories, get, *, allow
      g, 144a37fa-cc9d-4fc9-bf8a-a09999818504, role:readonly

controller:
  replicas: 1
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi

repoServer:
  replicas: 1
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

applicationSet:
  replicaCount: 1
  podAnnotations:
    oremus-labs.com/component: applicationset

server:
  extraArgs:
  - --insecure
  # extraEnv is not required when Argo substitutes from argocd-secret keys
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  service:
    type: ClusterIP
  autoscaling:
    enabled: false
  ingress:
    enabled: false
    tls: []

notifications:
  metrics:
    enabled: true

redis:
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 256Mi
  volumeMounts:
  - name: redis-data
    mountPath: /data
  volumes:
  - name: redis-data
    persistentVolumeClaim:
      claimName: argocd-redis
