global:
  revisionHistoryLimit: 5

configs:
  params:
    controller.operation.processors: "10"
    controller.status.processors: "20"
    applicationsetcontroller.log.format: json
  cm:
    url: https://argocd.oremuslabs.app
    timeout.reconciliation: 60s
    admin.enabled: "true"
    resource.customizations.health.apps_Deployment: |
      hs = {}
      if obj.status ~= nil and obj.status.availableReplicas ~= nil and obj.status.replicas ~= nil and obj.status.availableReplicas == obj.status.replicas then
        hs.status = "Healthy"
      else
        hs.status = "Progressing"
      end
      return hs
  repositories:
    ol-kubernetes-cluster:
      url: https://github.com/Oremus-Labs/ol-kubernetes-cluster.git

controller:
  replicas: 1
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi

repoServer:
  replicas: 1
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

applicationSet:
  replicaCount: 1
  podAnnotations:
    oremus-labs.com/component: applicationset

server:
  extraArgs:
  - --insecure
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  service:
    type: ClusterIP
  autoscaling:
    enabled: false
  ingress:
    enabled: false
    tls: []

notifications:
  metrics:
    enabled: true

redis:
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 256Mi
  volumeMounts:
  - name: redis-data
    mountPath: /data
  volumes:
  - name: redis-data
    persistentVolumeClaim:
      claimName: argocd-redis
