apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: oremuslabs-app-wildcard
  namespace: traefik
spec:
  secretName: oremuslabs-app-wildcard-tls
  issuerRef:
    name: cloudflare-dns
    kind: ClusterIssuer
  commonName: "*.oremuslabs.app"
  dnsNames:
  - "*.oremuslabs.app"
  - oremuslabs.app
