apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  itemPath: "vaults/fekk46izlezqrgocthhcn4xwp4/items/uoehc7luujcnyehrqz5enroisi"
