apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
  annotations:
    operator.1password.io/item-path: "op://oremuslabs.app/cloudflare-api-token"
stringData:
  token: op://oremuslabs.app/cloudflare-api-token/credential
