apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: smb-data
  namespace: smb
  labels:
    app: smb-server
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Ti
  storageClassName: sun-local-smb
