apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  # Mirrors op://oremuslabs.app/cloudflare-api-token /credential
  # Item has a trailing space in the title, so use the stable item UUID.
  itemPath: "vaults/oremuslabs.app/items/uoehc7luujcnyehrqz5enroisi"
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-cloudflare
spec:
  acme:
    email: ops@oremuslabs.app
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-cloudflare-account-key
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: credential
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-oremuslabs-app
  namespace: traefik-v3
spec:
  secretName: wildcard-oremuslabs-app-tls
  issuerRef:
    name: letsencrypt-cloudflare
    kind: ClusterIssuer
  dnsNames:
    - oremuslabs.app
    - '*.oremuslabs.app'
