apiVersion: batch/v1
kind: Job
metadata:
  name: longhorn-node-tag
  namespace: longhorn-system
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      serviceAccountName: longhorn-node-tag-sa
      restartPolicy: OnFailure
      containers:
      - name: kubectl
        image: bitnami/kubectl:latest
        command:
        - /bin/sh
        - -c
        - |
          kubectl patch nodes.longhorn.io sun -n longhorn-system --type merge -p '{"spec":{"tags":["minio","smb"],"disks":{"ol-raid":{"tags":["minio","smb"]}}}}'
