apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-minio
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
parameters:
  numberOfReplicas: "1"
  staleReplicaTimeout: "30"
  fromBackup: ""
  fsType: ext4
  diskSelector: minio
  nodeSelector: minio
  dataLocality: best-effort
  replicaAutoBalance: best-effort
