apiVersion: v1
kind: Service
metadata:
  name: kube-dns-lb
  namespace: kube-system
  annotations:
    metallb.universe.tf/address-pool: first-pool
spec:
  type: LoadBalancer
  loadBalancerIP: 10.10.10.55
  ports:
    - name: udp-53
      port: 53
      protocol: UDP
      targetPort: 53
    - name: tcp-53
      port: 53
      protocol: TCP
      targetPort: 53
  selector:
    k8s-app: kube-dns
