{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ printf "%s-netpol" (include "mcpo.fullname" .) }}
  namespace: {{ include "mcpo.namespace" . }}
  labels:
    {{- include "mcpo.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "mcpo.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ default "llm-core" .Values.global.namespaces.core }}
      ports:
        - port: {{ .Values.service.port }}
          protocol: TCP
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ default "llm-core" .Values.global.namespaces.core }}
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ default "llm-agents" .Values.global.namespaces.agents }}
      ports:
        - port: 8082
          protocol: TCP
        - port: 8083
          protocol: TCP
    {{- range .Values.networkPolicy.extraEgress }}
    - {{ toYaml . | nindent 6 }}
    {{- end }}
{{- end }}
