{{- $root := . -}}
{{- if $root.Values.onepasswordItems }}
  {{- range $key, $secret := $root.Values.onepasswordItems }}
    {{- if and $secret $secret.create $secret.onepassword.itemPath }}
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ $secret.name | default (printf "%s-%s" (include "mcpo.fullname" $root) $key) }}
  namespace: {{ include "mcpo.namespace" $root }}
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
    argocd.argoproj.io/tracking-id: {{ printf "%s:%s/%s" $root.Release.Name "OnePasswordItem" ($secret.name | default (printf "%s-%s" (include "mcpo.fullname" $root) $key)) }}
spec:
  itemPath: {{ $secret.onepassword.itemPath | quote }}
---
    {{- end }}
  {{- end }}
{{- end }}
