{{- if .Values.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ printf "%s-pdb" (include "mcpo.fullname" .) }}
  namespace: {{ include "mcpo.namespace" . }}
  labels:
    {{- include "mcpo.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "mcpo.selectorLabels" . | nindent 6 }}
{{- end }}
