apiVersion: batch/v1
kind: Job
metadata:
  name: headlamp-oidc-sync
  namespace: headlamp
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      serviceAccountName: headlamp-oidc-sync
      restartPolicy: OnFailure
      containers:
        - name: sync
          image: docker.io/bitnami/kubectl:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: headlamp-oidc
          command:
            - /bin/bash
            - -c
            - |
              set -euo pipefail
              kubectl -n headlamp create secret generic headlamp-oidc-env \
                --dry-run=client -o yaml \
                --from-literal=OIDC_CLIENT_ID="${clientID}" \
                --from-literal=OIDC_CLIENT_SECRET="${clientSecret}" \
                --from-literal=OIDC_ISSUER_URL="${issuerURL}" \
                --from-literal=OIDC_CALLBACK_URL="https://headlamp.oremuslabs.app/oidc-callback" \
                --from-literal=OIDC_SCOPES="${scopes}" \
                --from-literal=OIDC_VALIDATOR_CLIENT_ID="a9c2b807-718a-4aff-ab9c-a683a27bf7f9" \
                --from-literal=OIDC_VALIDATOR_ISSUER_URL="https://login.microsoftonline.com/abfcbee8-658f-4ab3-97f5-9b357e0f8cda/v2.0" \
                --from-literal=OIDC_USE_ACCESS_TOKEN="false" \
              | kubectl apply -f -
