apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: headlamp-oidc-sync
  namespace: headlamp
subjects:
  - kind: ServiceAccount
    name: headlamp-oidc-sync
    namespace: headlamp
roleRef:
  kind: Role
  name: headlamp-oidc-sync
  apiGroup: rbac.authorization.k8s.io
