apiVersion: batch/v1
kind: Job
metadata:
  name: headlamp-oidc-sync
  namespace: headlamp
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      serviceAccountName: headlamp-oidc-sync
      restartPolicy: OnFailure
      containers:
        - name: sync
          image: docker.io/bitnami/kubectl:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: headlamp-oidc
          command:
            - /bin/bash
            - -c
            - |
              set -euo pipefail
              kubectl -n headlamp create secret generic headlamp-oidc-env \
                --dry-run=client -o yaml \
                --from-literal=OIDC_CLIENT_ID="${clientID}" \
                --from-literal=OIDC_CLIENT_SECRET="${clientSecret}" \
                --from-literal=OIDC_ISSUER_URL="${issuerURL}" \
                --from-literal=OIDC_SCOPES="${scopes}" \
                --from-literal=OIDC_VALIDATOR_CLIENT_ID="${validatorClientID:-}" \
                --from-literal=OIDC_VALIDATOR_ISSUER_URL="${validatorIssuerURL:-}" \
                --from-literal=OIDC_USE_ACCESS_TOKEN="${useAccessToken:-false}" \
              | kubectl apply -f -
