apiVersion: batch/v1
kind: Job
metadata:
  name: headlamp-oidc-sync
  namespace: headlamp
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      serviceAccountName: headlamp-oidc-sync
      restartPolicy: OnFailure
      containers:
        - name: sync
          image: docker.io/bitnami/kubectl:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: headlamp-oidc
          command:
            - /bin/bash
            - -c
            - |
              set -euo pipefail
              APP_ID="${application_id}"
              TENANT="${tenant_id}"
              SECRET="${client_secret}"
              CALLBACK=$(printf '%s\n' "${headlamp_redirect_uris}" | head -n1)
              ISSUER_URL="https://login.microsoftonline.com/${TENANT}/v2.0"
              SCOPES="openid email profile offline_access"

              kubectl -n headlamp create secret generic headlamp-oidc-env \
                --dry-run=client -o yaml \
                --from-literal=OIDC_CLIENT_ID="${APP_ID}" \
                --from-literal=OIDC_CLIENT_SECRET="${SECRET}" \
                --from-literal=OIDC_ISSUER_URL="${ISSUER_URL}" \
                --from-literal=OIDC_CALLBACK_URL="${CALLBACK}" \
                --from-literal=OIDC_SCOPES="${SCOPES}" \
                --from-literal=OIDC_VALIDATOR_CLIENT_ID="${APP_ID}" \
                --from-literal=OIDC_VALIDATOR_ISSUER_URL="${ISSUER_URL}" \
                --from-literal=OIDC_USE_ACCESS_TOKEN="false" \
              | kubectl apply -f -
