apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: headlamp-oidc
  namespace: headlamp
spec:
  itemPath: "vaults/fekk46izlezqrgocthhcn4xwp4/items/yj5y22xdt6zde4xw4muossdm3i"
  template:
    data:
      clientID: "{{ if get .fields \"client-id\" }}{{ get .fields \"client-id\" }}{{ end }}"
      clientSecret: "{{ if get .fields \"secret-value\" }}{{ get .fields \"secret-value\" }}{{ end }}"
      issuerURL: "{{ if get .fields \"tenant-id\" }}{{ printf \"https://login.microsoftonline.com/%s/v2.0\" (get .fields \"tenant-id\") }}{{ end }}"
      scopes: "6dae42f8-4368-4678-94ff-3960e28e3630/user.read,openid,email,profile"
      validatorClientID: "6dae42f8-4368-4678-94ff-3960e28e3630"
      validatorIssuerURL: "{{ if get .fields \"directory-id\" }}{{ printf \"https://sts.windows.net/%s/\" (get .fields \"directory-id\") }}{{ end }}"
      useAccessToken: "true"
