apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cert-manager
  namespace: argocd
spec:
  generators:
    - clusters: {}
  template:
    metadata:
      name: '{{name}}-cert-manager'
    spec:
      project: platform
      destination:
        server: '{{server}}'
        namespace: cert-manager
      source:
        repoURL: https://charts.jetstack.io
        chart: cert-manager
        targetRevision: v1.17.2
        helm:
          values: |
            installCRDs: true
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
