apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: metallb-onprem
  namespace: argocd
spec:
  generators:
    - clusters: {}
  template:
    metadata:
      name: '{{name}}-metallb'
    spec:
      project: platform
      destination:
        server: '{{server}}'
        namespace: metallb-system
      sources:
        - repoURL: https://metallb.github.io/metallb
          chart: metallb
          targetRevision: 0.15.2
          helm:
            releaseName: metallb
            values: |
              crds:
                enabled: true
              speaker:
                frr:
                  enabled: false
                arp:
                  enabled: true
                  strict: true
        - repoURL: https://github.com/Oremus-Labs/ol-kubernetes-cluster
          targetRevision: HEAD
          path: apps/platform/metallb/config
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
