apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: minio-root-credentials
  namespace: minio
spec:
  itemPath: "vaults/fekk46izlezqrgocthhcn4xwp4/items/gyx7jfbgz3cba4m2vkfv2bywiy"
