apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: onepassword-connect-helm
  namespace: argocd
spec:
  generators:
    - clusters: {}
  template:
    metadata:
      name: '{{name}}-1password-connect-helm'
      annotations:
        argocd.argoproj.io/sync-wave: "60"
    spec:
      project: workloads
      destination:
        server: '{{server}}'
        namespace: onepassword
      source:
        repoURL: https://1password.github.io/connect-helm-charts/
        chart: connect
        targetRevision: 2.0.0 # pin a version; update as needed
        helm:
          valueFiles: []
          values: |
            # Fallback minimal values if provider-specific file not loaded.
            connect:
              enabled: true
              existingSecret: op-credentials
            operator:
              create: true
              token:
                existingSecret: onepassword-connect-token
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      ignoreDifferences:
        - group: apps
          kind: Deployment
          jsonPointers:
            - /spec/template/spec/containers/0/image
  # Use matrix to overlay provider-specific Helm values when supported (future enhancement).
