apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: onepassword-connect
  namespace: argocd
spec:
  generators:
    - clusters: {}
  template:
    metadata:
      name: '{{name}}-1password-connect'
    spec:
      project: workloads
      destination:
        server: '{{server}}'
        namespace: onepassword
      source:
        repoURL: https://github.com/Oremus-Labs/ol-kubernetes-cluster
        targetRevision: HEAD
        path: apps/workloads/1password-connect/overlays/{{metadata.labels.provider}}
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
