apiVersion: v1
kind: Service
metadata:
  name: coredns-lb
  namespace: kube-system
  annotations:
    oremus-labs.com/managed-by: gitops
spec:
  type: LoadBalancer
  loadBalancerIP: 10.10.10.53
  selector:
    k8s-app: coredns
  ports:
  - name: dns-udp
    port: 53
    protocol: UDP
    targetPort: 53
  - name: dns-tcp
    port: 53
    protocol: TCP
    targetPort: 53
