apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-knative-serving
  namespace: argocd
  labels:
    oremus-labs.com/tier: platform
spec:
  project: platform
  source:
    repoURL: https://github.com/Oremus-Labs/ol-kubernetes-cluster.git
    targetRevision: main
    path: apps/platform/knative-serving
  destination:
    server: https://kubernetes.default.svc
    namespace: knative-serving
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
