apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: oremus-labs-workloads
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - name: homepage
        namespace: homepage
        project: workloads
        path: apps/workloads/homepage/chart
        targetRevision: main
        imageTag: latest
      - name: proxy-urls
        namespace: traefik
        project: workloads
        path: apps/workloads/proxy-urls/chart
        targetRevision: main
        imageTag: latest
  template:
    metadata:
      name: workloads-{{name}}
      labels:
        oremus-labs.com/tier: workloads
    spec:
      project: '{{project}}'
      source:
        repoURL: https://github.com/Oremus-Labs/ol-kubernetes-cluster.git
        targetRevision: '{{targetRevision}}'
        path: '{{path}}'
        helm:
          valueFiles:
          - values.yaml
          parameters:
          - name: image.tag
            value: '{{imageTag}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
