apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: oremus-labs-workloads
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - name: homepage
        namespace: homepage
        project: workloads
        path: apps/workloads/homepage/chart
        targetRevision: main
        imageTag: latest
      - name: proxy-urls
        namespace: traefik
        project: workloads
        path: apps/workloads/proxy-urls/chart
        targetRevision: main
        imageTag: latest
      - name: searxng
        namespace: searxng
        project: workloads
        path: apps/workloads/searxng/chart
        targetRevision: main
        imageTag: latest
      - name: open-webui
        namespace: open-webui
        project: workloads
        path: apps/workloads/open-webui/chart
        targetRevision: main
        imageTag: "0.6.36"
      - name: kubernetes-mcp-server
        namespace: kubernetes-mcp
        project: workloads
        path: apps/workloads/kubernetes-mcp-server/chart
        targetRevision: main
        imageTag: latest
      - name: docker-mcp
        namespace: docker-mcp
        project: workloads
        path: apps/workloads/docker-mcp/chart
        targetRevision: main
        imageTag: latest
      - name: duckduckgo-mcp
        namespace: duckduckgo-mcp
        project: workloads
        path: apps/workloads/duckduckgo-mcp/chart
        targetRevision: main
        imageTag: latest
      - name: firecrawl
        namespace: firecrawl
        project: workloads
        path: apps/workloads/firecrawl/chart
        targetRevision: main
        imageTag: "0.1.0"
      - name: filesystem-mcp
        namespace: filesystem-mcp
        project: workloads
        path: apps/workloads/filesystem-mcp/chart
        targetRevision: main
        imageTag: "1.24-bookworm"
      - name: github-mcp
        namespace: github-mcp
        project: workloads
        path: apps/workloads/github-mcp/chart
        targetRevision: main
        imageTag: "3.12-slim"
      - name: n8n-mcp
        namespace: n8n-mcp
        project: workloads
        path: apps/workloads/n8n-mcp/chart
        targetRevision: main
        imageTag: "latest"
      - name: n8n
        namespace: n8n
        project: workloads
        path: apps/workloads/n8n/chart
        targetRevision: main
        imageTag: "1.121.3"
      - name: deep-research-postgres
        namespace: deep-research
        project: workloads
        path: apps/workloads/deep-research-postgres/chart
        targetRevision: main
        imageTag: "15.8"
      - name: deep-research-qdrant
        namespace: deep-research
        project: workloads
        path: apps/workloads/deep-research-qdrant/chart
        targetRevision: main
        imageTag: v1.11.0
      - name: deep-research-embedding
        namespace: deep-research
        project: workloads
        path: apps/workloads/deep-research-embedding/chart
        targetRevision: main
        imageTag: "cpu-latest"
      - name: deep-research-orchestrator
        namespace: deep-research
        project: workloads
        path: apps/workloads/deep-research-orchestrator/chart
        targetRevision: main
        imageTag: "heartbeat-cleanup"
      - name: deep-research-ui
        namespace: deep-research
        project: workloads
        path: apps/workloads/deep-research-ui/chart
        targetRevision: main
        imageTag: "ui-phase-b5"
  template:
    metadata:
      name: workloads-{{name}}
      labels:
        oremus-labs.com/tier: workloads
    spec:
      project: '{{project}}'
      source:
        repoURL: https://github.com/Oremus-Labs/ol-kubernetes-cluster.git
        targetRevision: '{{targetRevision}}'
        path: '{{path}}'
        helm:
          releaseName: '{{name}}'
          valueFiles:
          - values.yaml
          parameters:
          - name: image.tag
            value: '{{imageTag}}'
          - name: datastore.driver
            value: postgres
          - name: datastore.dsn
            value: postgresql://modelmanager:modelmanager-secret@model-manager-postgres-postgresql.ai.svc.cluster.local:5432/modelmanager?sslmode=disable
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
