apiVersion: v1
kind: Service
metadata:
  name: {{ include "triton-vllm.fullname" . }}-metrics
  labels:
    {{- include "triton-vllm.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "triton-vllm.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: metrics
      port: {{ .Values.service.metricsPort }}
      targetPort: metrics
