apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
  namespace: argocd
stringData:
  # Replace with the bcrypt hash stored in 1Password (`op://oremuslabs.app/argocd-admin-password/password`).
  admin.password: "$2a$10$nx/n3bG9mfHN0Hylfz9ME.haoBuvQMOVJRK/DE0dWJt.2vrznQyoi"
  # Update to the UTC timestamp when the password was generated so Argo CD detects the rotation.
  admin.passwordMtime: "2025-11-13T02:53:14Z"
