apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-sun-minio
  labels:
    app: minio
spec:
  capacity:
    storage: 3Ti
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: sun-local-minio
  local:
    path: /mnt/ol/minio
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - sun
