apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-sun-smb
  labels:
    app: smb-server
spec:
  capacity:
    storage: 1Ti
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: sun-local-smb
  local:
    path: /mnt/ol/smb
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - sun
