apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sun-local-minio
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
allowVolumeExpansion: false
